### ISSUE TITLE
tests_require not complete

### ISSUE THREAD

**Issue by jayvdb** [chfw/lml#11]
On Python 2.7, the tests need mock, and `six` is also mentioned in `tests/requirements.txt` but I can not see it mentioned in the source of the tests.

Even with them both installed on openSUSE, there is an interesting error at https://github.com/chfw/lml/blob/master/tests/test_utils.py#L16
`import pyexcel_test`

```py
======================================================================
ERROR: test_utils.test_do_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/abuild/rpmbuild/BUILD/lml-0.0.8/tests/test_utils.py", line 17, in test_do_import
    import pyexcel_test
ImportError: No module named pyexcel_test
```

and also two others like

```py
======================================================================
ERROR: test_plugin_loader.test_load_plugins
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/abuild/rpmbuild/BUILD/lml-0.0.8/tests/test_plugin_loader.py", line 39, in test_load_plugins
    info = CACHED_PLUGIN_INFO["test_io"][0]
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
lml.loader: DEBUG: scanning for plugins...
lml.utils: ERROR: pyexcel_test is abscent or cannot be imported
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/lml-0.0.8/lml/utils.py", line 42, in do_import
    return _do_import(plugin_module_name)
  File "/home/abuild/rpmbuild/BUILD/lml-0.0.8/lml/utils.py", line 51, in _do_import
    plugin_module = __import__(plugin_module_name)
ImportError: No module named pyexcel_test
lml.loader: DEBUG: pyexcel_test
lml.loader: DEBUG: No module named pyexcel_test
lml.loader: DEBUG: ignored pyexcel_io
lml.loader: DEBUG: scanning done
--------------------- >> end captured logging << ---------------------
```

https://build.opensuse.org/package/live_build_log/home:jayvdb:soe/python-lml/openSUSE_Tumbleweed/x86_64

It might be related to different versions of `six` ..?

**Comment by jayvdb** [comment]
The spec file and tarball being used is at https://build.opensuse.org/package/show/home:jayvdb:soe/python-lml

**Comment by chfw** [comment]
there were two test folders not included (pyexcel_test). I have removed six from tests/requirements.txt.

do you need tests/requirements.txt specified in setup.py?
